"""
Django settings for tri_cloud_vault project.
Generated by 'django-admin startproject'
"""

from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import os

load_dotenv()
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# --------------------------------------------------
# BASE
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-dev-key")

# Read from environment — set DEBUG=True in your .env for local dev,
# leave it unset (or set DEBUG=False) in production
DEBUG = os.getenv("DEBUG", "False") == "True"

# --------------------------------------------------
# HOSTS
# --------------------------------------------------

ALLOWED_HOSTS = [
    "charansai.me",
    ".charansai.me",        # allow all subdomains
    "localhost",
    "127.0.0.1",
    ".elb.amazonaws.com"
]

CSRF_TRUSTED_ORIGINS = [
    "https://charansai.me",
    "https://tricloudvault.charansai.me",
    "https://www.charansai.me",
]

# --------------------------------------------------
# FILE UPLOAD LIMITS
# --------------------------------------------------
FILE_UPLOAD_MAX_MEMORY_SIZE = 0 
DATA_UPLOAD_MAX_MEMORY_SIZE = None
# --------------------------------------------------
# APPLICATIONS
# --------------------------------------------------

INSTALLED_APPS = [
    "jazzmin",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',

    # Third-party
    "rest_framework",
    "corsheaders",

    # Local apps
    "accounts",
    "files",
    "clouds",
    "dashboard",
    "payments",
]

JAZZMIN_SETTINGS = {

    "site_title": "TriCloud Vault Admin",
    "site_header": "TriCloud Vault",
    "site_brand": "TriCloud Vault",

    "icons": {
        "accounts.User": "fas fa-users",
        "files.File": "fas fa-file",
        "payments.Payment": "fas fa-credit-card",
        "payments.Subscription": "fas fa-crown",
        "auth.Group": "fas fa-users-cog",
    },

    "custom_links": {
        "auth": [{
            "name": "User Groups",
            "url": "admin:auth_group_changelist",
            "icon": "fas fa-users-cog",
        }]
    },

    "hide_apps": [
        "auth"
    ],
}

# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# --------------------------------------------------
# CORS
# --------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://charansai.me",
    "https://www.charansai.me",
    "http://localhost:5500",
    "http://127.0.0.1:5500",
]

# allow ALL subdomains like app.charansai.me
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.charansai\.me$",
]

# --------------------------------------------------
# URL / TEMPLATES
# --------------------------------------------------

ROOT_URLCONF = "tri_cloud_vault.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tri_cloud_vault.wsgi.application"

# --------------------------------------------------
# DATABASE (POSTGRES)
# --------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        # Reuse TCP connections for 60 seconds instead of opening a new
        # connection to Postgres on every single HTTP request
        "CONN_MAX_AGE": 60,
    }
}

# --------------------------------------------------
# AUTH
# --------------------------------------------------

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# --------------------------------------------------
# DRF (NO BROWSABLE API)
# --------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}

# --------------------------------------------------
# JWT
# --------------------------------------------------

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=72),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# --------------------------------------------------
# EMAIL
# --------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = "TriCloud Vault <charansairamisetti@gmail.com>"

# --------------------------------------------------
# LOGGING
# --------------------------------------------------

LOGS_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOGS_DIR, exist_ok=True)
 
LOGGING = {
    "version":                  1,
    "disable_existing_loggers": False,
 
    "formatters": {
        "benchmark": {
            # Pipe-delimited so the log is directly parseable by pandas
            # after the experiment: pd.read_csv("django.log", sep="|")
            "format":  "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
 
    "handlers": {
        "console": {
            "class":     "logging.StreamHandler",
            "formatter": "benchmark",
        },
        "file": {
            # Rotating handler prevents the log from growing unbounded
            # across a 2-3 day benchmark run
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    os.path.join(LOGS_DIR, "django.log"),
            "maxBytes":    50 * 1024 * 1024,   # 50 MB per file
            "backupCount": 5,                   # keep last 5 rotated files
            "formatter":   "benchmark",
        },
    },
 
    "loggers": {
        # Django request logger — one line per HTTP request with status code
        "django.request": {
            "handlers":  ["file", "console"],
            "level":     "INFO",
            "propagate": False,
        },
        # Application benchmark logger — upload timings from views.py
        "benchmark": {
            "handlers":  ["file", "console"],
            "level":     "DEBUG",
            "propagate": False,
        },
        # Suppress per-query DB logs — too noisy during bulk benchmark runs
        "django.db.backends": {
            "handlers":  ["file"],
            "level":     "WARNING",
            "propagate": False,
        },
        # Suppress per-chunk SDK debug output from cloud provider libraries
        "botocore": {
            "handlers":  ["file"],
            "level":     "WARNING",
            "propagate": False,
        },
        "azure": {
            "handlers":  ["file"],
            "level":     "WARNING",
            "propagate": False,
        },
        "google": {
            "handlers":  ["file"],
            "level":     "WARNING",
            "propagate": False,
        },
    },
 
    "root": {
        "handlers": ["file", "console"],
        "level":    "INFO",
    },
}

# --------------------------------------------------
# SECURITY HEADERS
# --------------------------------------------------

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"